import { Product, Category, MerchantSettings, ThemeSettings, SiteContent } from './types';

// ─── Categories ─────────────────────────────────────────────────────────────

export const CATEGORIES: Category[] = [
  { id: 'all', slug: 'all', name: { en: 'All Products', np: 'सबै उत्पादन' } },
  { id: 'cat-kurthas', slug: 'cat-kurthas', name: { en: 'Kurthas & Sets', np: 'कुर्ता तथा सेट' } },
  { id: 'cat-sarees', slug: 'cat-sarees', name: { en: 'Sarees', np: 'साडी' } },
  { id: 'cat-lehengas', slug: 'cat-lehengas', name: { en: 'Lehengas', np: 'लहेंगा' } },
  { id: 'cat-accessories', slug: 'cat-accessories', name: { en: 'Accessories', np: 'गहना तथा एक्सेसरिज' } },
  { id: 'cat-festive', slug: 'cat-festive', name: { en: 'Festive Collection', np: 'चाड पर्व संग्रह' } },
];

// ─── Mock Products ───────────────────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'daw-001',
    slug: 'crimson-heritage-silk-kurtha',
    title: { en: 'Crimson Heritage Silk Kurtha Set', np: 'रातो मौलिक सिल्क कुर्ता सेट' },
    description: {
      en: 'Handcrafted pure silk kurtha with intricate gold zari threadwork, tailored for festive moments and cultural celebrations.',
      np: 'मौलिक शुद्ध सिल्क र सुनौलो जरी बुट्टाले सजिएको आकर्षक नेपाली फेसन, चाडपर्वको लागि।',
    },
    price: 5400,
    originalPrice: 6800,
    categoryId: 'cat-kurthas',
    categoryName: { en: 'Kurthas & Sets', np: 'कुर्ता तथा सेट' },
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1609873814058-a8928924184a?auto=format&fit=crop&w=800&q=80',
    ],
    availableSizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    rating: 4.9,
    reviewCount: 42,
    tags: ['kurtha', 'silk', 'festive', 'zari'],
    fabric: { en: 'Pure Mulberry Silk', np: 'शुद्ध मलबेरी सिल्क' },
    origin: { en: 'Kathmandu Atelier, Nepal', np: 'काठमाडौँ, नेपाल' },
    isNewArrival: false,
    isFeatured: true,
  },
  {
    id: 'daw-002',
    slug: 'ivory-handloom-cotton-kurtha',
    title: { en: 'Ivory Handloom Cotton Kurtha', np: 'सेतो हातेतान सुती कुर्ता' },
    description: {
      en: 'Breezy handloom cotton kurtha with delicate hand-block prints, perfect for everyday elegance.',
      np: 'हातेतान सुती कुर्ता, दैनिक सुन्दरताको लागि आदर्श।',
    },
    price: 3200,
    originalPrice: 4000,
    categoryId: 'cat-kurthas',
    categoryName: { en: 'Kurthas & Sets', np: 'कुर्ता तथा सेट' },
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    ],
    availableSizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    rating: 4.7,
    reviewCount: 28,
    tags: ['kurtha', 'cotton', 'handloom', 'everyday'],
    fabric: { en: 'Handloom Cotton', np: 'हातेतान सुती' },
    origin: { en: 'Bhaktapur, Nepal', np: 'भक्तपुर, नेपाल' },
    isNewArrival: true,
    isFeatured: true,
  },
  {
    id: 'daw-003',
    slug: 'royal-banarasi-saree',
    title: { en: 'Royal Banarasi Silk Saree', np: 'रोयल बनारसी सिल्क साडी' },
    description: {
      en: 'Opulent Banarasi silk saree woven with golden meenakari motifs, a timeless heirloom piece.',
      np: 'सुनौलो मीनाकारी बुट्टासहितको शाही बनारसी साडी।',
    },
    price: 12500,
    originalPrice: 15000,
    categoryId: 'cat-sarees',
    categoryName: { en: 'Sarees', np: 'साडी' },
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    ],
    availableSizes: ['Free Size'],
    inStock: true,
    rating: 5.0,
    reviewCount: 19,
    tags: ['saree', 'banarasi', 'silk', 'wedding'],
    fabric: { en: 'Pure Banarasi Silk', np: 'शुद्ध बनारसी सिल्क' },
    origin: { en: 'Kathmandu Atelier, Nepal', np: 'काठमाडौँ, नेपाल' },
    isNewArrival: false,
    isFeatured: true,
  },
  {
    id: 'daw-004',
    slug: 'dusty-rose-georgette-saree',
    title: { en: 'Dusty Rose Georgette Saree', np: 'डस्टी रोज जर्जेट साडी' },
    description: {
      en: 'Lightweight georgette saree in a romantic dusty rose shade with delicate embroidery borders.',
      np: 'हल्का जर्जेट साडी, डस्टी रोज रंगमा।',
    },
    price: 6800,
    originalPrice: 8200,
    categoryId: 'cat-sarees',
    categoryName: { en: 'Sarees', np: 'साडी' },
    images: [
      'https://images.unsplash.com/photo-1620510625142-b45cbb784397?auto=format&fit=crop&w=800&q=80',
    ],
    availableSizes: ['Free Size'],
    inStock: true,
    rating: 4.8,
    reviewCount: 33,
    tags: ['saree', 'georgette', 'party', 'embroidery'],
    fabric: { en: 'Pure Georgette', np: 'शुद्ध जर्जेट' },
    origin: { en: 'Kathmandu Atelier, Nepal', np: 'काठमाडौँ, नेपाल' },
    isNewArrival: true,
    isFeatured: false,
  },
  {
    id: 'daw-005',
    slug: 'bridal-red-lehenga',
    title: { en: 'Bridal Crimson Lehenga Choli', np: 'ब्राइडल रातो लहेंगा चोली' },
    description: {
      en: 'Magnificent bridal lehenga in deep crimson with heavy zardozi embroidery and dupatta. A dream for every bride.',
      np: 'गाढा रातो रंगको भव्य दुलहीको लहेंगा, जर्दोजी काम र दुपट्टासहित।',
    },
    price: 28000,
    originalPrice: 35000,
    categoryId: 'cat-lehengas',
    categoryName: { en: 'Lehengas', np: 'लहेंगा' },
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
    ],
    availableSizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    rating: 4.9,
    reviewCount: 12,
    tags: ['lehenga', 'bridal', 'wedding', 'zardozi'],
    fabric: { en: 'Heavy Silk & Net', np: 'भारी सिल्क र नेट' },
    origin: { en: 'Kathmandu Atelier, Nepal', np: 'काठमाडौँ, नेपाल' },
    isNewArrival: false,
    isFeatured: true,
  },
  {
    id: 'daw-006',
    slug: 'mint-anarkali-lehenga',
    title: { en: 'Mint Green Anarkali Lehenga', np: 'मिन्ट हरियो अनारकली लहेंगा' },
    description: {
      en: 'Flowing mint green anarkali lehenga with floral threadwork, perfect for sangeet and mehndi occasions.',
      np: 'फूलको बुट्टा भएको मिन्ट हरियो अनारकली लहेंगा।',
    },
    price: 14500,
    originalPrice: 18000,
    categoryId: 'cat-lehengas',
    categoryName: { en: 'Lehengas', np: 'लहेंगा' },
    images: [
      'https://images.unsplash.com/photo-1609873814058-a8928924184a?auto=format&fit=crop&w=800&q=80',
    ],
    availableSizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    rating: 4.7,
    reviewCount: 24,
    tags: ['lehenga', 'anarkali', 'mint', 'party'],
    fabric: { en: 'Faux Georgette & Net', np: 'जर्जेट र नेट' },
    origin: { en: 'Kathmandu Atelier, Nepal', np: 'काठमाडौँ, नेपाल' },
    isNewArrival: true,
    isFeatured: false,
  },
  {
    id: 'daw-007',
    slug: 'gold-temple-jhumkas',
    title: { en: 'Gold Temple Jhumka Earrings', np: 'सुनको मन्दिर झुम्का' },
    description: {
      en: 'Traditional temple-style gold-plated jhumka earrings with ruby stones and delicate filigree work.',
      np: 'रुबी पत्थर र फिलिग्री कामसहितको सुनको मन्दिर शैलीको झुम्का।',
    },
    price: 2800,
    originalPrice: 3500,
    categoryId: 'cat-accessories',
    categoryName: { en: 'Accessories', np: 'गहना तथा एक्सेसरिज' },
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
    ],
    availableSizes: ['Free Size'],
    inStock: true,
    rating: 4.8,
    reviewCount: 56,
    tags: ['jewellery', 'earrings', 'jhumka', 'gold', 'temple'],
    origin: { en: 'Kathmandu Atelier, Nepal', np: 'काठमाडौँ, नेपाल' },
    isNewArrival: false,
    isFeatured: false,
  },
  {
    id: 'daw-008',
    slug: 'dashain-festive-kurtha-set',
    title: { en: 'Dashain Festive Kurtha Set', np: 'दशैं उत्सव कुर्ता सेट' },
    description: {
      en: 'Specially curated kurtha set for Dashain celebrations with embroidered neckline and matching palazzo.',
      np: 'दशैंको लागि विशेष रूपमा बनाइएको कुर्ता सेट।',
    },
    price: 4800,
    originalPrice: 6000,
    categoryId: 'cat-festive',
    categoryName: { en: 'Festive Collection', np: 'चाड पर्व संग्रह' },
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    ],
    availableSizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    rating: 4.9,
    reviewCount: 38,
    tags: ['festive', 'dashain', 'kurtha', 'limited'],
    fabric: { en: 'Cotton Silk Blend', np: 'कटन सिल्क मिश्रण' },
    origin: { en: 'Kathmandu Atelier, Nepal', np: 'काठमाडौँ, नेपाल' },
    isNewArrival: true,
    isFeatured: true,
  },
];

// ─── Default Store Settings ──────────────────────────────────────────────────

export const DEFAULT_MERCHANT: MerchantSettings = {
  shopName: { en: 'DAWOSTI Boutique', np: 'दावोस्ती बुटिक' },
  shopTagline: { en: 'Authentic Nepali Fashion', np: 'मौलिक नेपाली फेसन' },
  shopPhone: '9708251494',
  shopEmail: 'contact.dawosti@gmail.com',
  shopAddress: { en: 'Kathmandu, Nepal', np: 'काठमाडौँ, नेपाल' },
  whatsappNumber: '9779708251494',
  freeDeliveryThreshold: 3000,
  deliveryFee: 150,
};

export const DEFAULT_THEME: ThemeSettings = {
  isDashainTheme: false,
  discountPercentage: 0,
  couponCode: '',
  bannerText: {
    en: '🎉 Free delivery on orders above NPR 3,000 | Handcrafted in Nepal',
    np: '🎉 NPR ३,०००  माथिको अर्डरमा निःशुल्क डेलिभरी | नेपालमा हस्तनिर्मित',
  },
  accentColor: '#8B3A3A',
  showAnnouncementBar: true,
};

export const DEFAULT_SITE_CONTENT: SiteContent = {
  heroHeadline: { en: 'Wear the Soul of Nepal', np: 'नेपालको आत्मा लगाउनुहोस्' },
  heroSubtext: {
    en: 'Handcrafted luxury fashion from the heart of Kathmandu',
    np: 'काठमाडौँको मुटुबाट हस्तनिर्मित लक्जरी फेसन',
  },
  aboutText: {
    en: 'DAWOSTI is a boutique fashion house celebrating authentic Nepali craftsmanship.',
    np: 'दावोस्ती एक बुटिक फेसन घर हो जसले मौलिक नेपाली शिल्पकारिता मनाउँछ।',
  },
};
